[arkalia_score]
timestamp = "2025-07-04T20:22:52.058212"
global_score = 0.654
status = "good"
alerts_count = 3

[arkalia_score.components]
zeroia_confidence = 0.5
reflexia_alerts = 0
sandozia_integrity = 0.5
cognitive_load = 0.275
system_health = 0.6

[arkalia_score.thresholds]
zeroia_confidence = 0.7
reflexia_alerts = 5
sandozia_integrity = 0.8
cognitive_load = 0.6
system_health = 0.8
