---
groups:
  - name: arkalia-alerts
    rules:
      # Alertes système critiques
      - alert: ArkaliaHighCPU
        expr: arkalia_cpu_usage_percent > 80
        for: 2m
        labels:
          severity: warning
          service: arkalia
        annotations:
          summary: "CPU élevé sur Arkalia"
          description: "L'utilisation CPU dépasse 80% depuis 2 minutes"
          value: "{{ $value }}%"

      - alert: ArkaliaHighMemory
        expr: arkalia_memory_usage_bytes / 1024 / 1024 / 1024 > 6
        for: 2m
        labels:
          severity: warning
          service: arkalia
        annotations:
          summary: "Mémoire élevée sur Arkalia"
          description: "L'utilisation mémoire dépasse 6GB depuis 2 minutes"
          value: "{{ $value }}GB"

      # Alertes modules
      - alert: ModuleInactive
        expr: arkalia_modules_status == 0
        for: 1m
        labels:
          severity: critical
          service: arkalia
        annotations:
          summary: "Module Arkalia inactif"
          description: "Le module {{ $labels.module_name }} est inactif"
          module: "{{ $labels.module_name }}"

      - alert: ZeroIALowConfidence
        expr: arkalia_zeroia_confidence_score < 0.3
        for: 5m
        labels:
          severity: warning
          service: zeroia
        annotations:
          summary: "Confiance ZeroIA faible"
          description: "Le score de confiance ZeroIA est inférieur à 30%"
          value: "{{ $value }}"

      - alert: AssistantIASlowResponse
        expr: histogram_quantile(0.95, rate(arkalia_assistantia_response_time_seconds_bucket[5m])) > 5
        for: 2m
        labels:
          severity: warning
          service: assistantia
        annotations:
          summary: "Réponse AssistantIA lente"
          description: "Le temps de réponse P95 dépasse 5 secondes"
          value: "{{ $value }}s"

      # Alertes API
      - alert: HighErrorRate
        expr: rate(arkalia_requests_total{status=~"5.."}[5m]) / rate(arkalia_requests_total[5m]) > 0.05
        for: 2m
        labels:
          severity: critical
          service: arkalia-api
        annotations:
          summary: "Taux d'erreur élevé"
          description: "Plus de 5% des requêtes retournent une erreur 5xx"
          value: "{{ $value | humanizePercentage }}"

      - alert: HighRequestLatency
        expr: histogram_quantile(0.95, rate(arkalia_request_duration_seconds_bucket[5m])) > 2
        for: 2m
        labels:
          severity: warning
          service: arkalia-api
        annotations:
          summary: "Latence API élevée"
          description: "Le temps de réponse P95 dépasse 2 secondes"
          value: "{{ $value }}s"

      - alert: NoRequests
        expr: rate(arkalia_requests_total[5m]) == 0
        for: 5m
        labels:
          severity: warning
          service: arkalia-api
        annotations:
          summary: "Aucune requête API"
          description: "Aucune requête reçue depuis 5 minutes"

      # Alertes ReflexIA
      - alert: ReflexIAHighLatency
        expr: arkalia_reflexia_latency_ms > 100
        for: 2m
        labels:
          severity: warning
          service: reflexia
        annotations:
          summary: "Latence ReflexIA élevée"
          description: "La latence système dépasse 100ms"
          value: "{{ $value }}ms"

      - alert: ReflexIAHighResourceUsage
        expr: arkalia_reflexia_cpu_usage_percent > 90 or arkalia_reflexia_ram_usage_percent > 90
        for: 2m
        labels:
          severity: critical
          service: reflexia
        annotations:
          summary: "Utilisation ressources ReflexIA critique"
          description: "CPU ou RAM dépasse 90%"
          value: "CPU: {{ $value }}%"

      # Alertes de sécurité
      - alert: SecurityBlocks
        expr: rate(arkalia_assistantia_security_blocks_total[5m]) > 0
        for: 1m
        labels:
          severity: info
          service: assistantia
        annotations:
          summary: "Blocages de sécurité détectés"
          description: "Des prompts ont été bloqués par les filtres de sécurité"
          value: "{{ $value }} blocs/min"

      # Alertes de performance
      - alert: HighRateLimit
        expr: rate(arkalia_assistantia_rate_limits_total[5m]) > 10
        for: 2m
        labels:
          severity: warning
          service: assistantia
        annotations:
          summary: "Rate limiting fréquent"
          description: "Plus de 10 rate limits par minute"
          value: "{{ $value }} limits/min"

      # Alertes de santé système
      - alert: SystemUnhealthy
        expr: arkalia_system_health == 0
        for: 1m
        labels:
          severity: critical
          service: arkalia
        annotations:
          summary: "Système Arkalia non sain"
          description: "Le système Arkalia signale un état non sain"

      - alert: CriticalFilesMissing
        expr: arkalia_critical_files_count < 8
        for: 1m
        labels:
          severity: critical
          service: arkalia
        annotations:
          summary: "Fichiers critiques manquants"
          description: "Des fichiers critiques du système sont manquants"
          value: "{{ $value }}/8 fichiers"
