---
# deployment/render_helloria.yml
services:
  helloria:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - 8000:8000
    environment:
      - ENV=production
    command: ["uvicorn", "helloria.core:app", "--host", "0.0.0.0", "--port", "8000"]
