[status]
cpu = 72.1
ram = 65.4
latency = 1.7
llm_response_quality = "high"

[chat]
last_prompt = "Analyse l'état du système."
last_sentiment = "neutre"

[reflexia]
last_snapshot = "normal"
last_alert = "none"
