# 🧠 Snapshot réflexif — ZeroIA
# 📅 Généré automatiquement à chaque boucle

[snapshot_1]
[timestamp]
datetime = "2025-06-25T14:30:00Z"
timezone = "UTC"

[inputs]
cpu = 91
ram = 78
severity = "critical"
reflexia_status = "alert"
previous_decision = "cooldown_activated"

[decision]
action = "adjust_threshold"
confidence_score = 0.93
source = "reason_loop"
reflexia_consistency = "conflicting"

[meta]
last_decision_reason = "Thresholds exceeded and ReflexIA reported anomaly"
question_to_self = "Did I overreact to a transient spike? Should I wait longer next time?"
self_assessment = "partially justified"

[context]
reflexia_trace_id = "rf-20250625-0421"
assistantia_context = "no contradiction detected"
global_state_checksum = "7f8d49eaae10ef2c"

[snapshot_2]
timestamp = "2025-06-25T14:50:12"
status = "critical"
context_source = "reflexia_snapshot_20250625.json"

[snapshot_2.inputs]
cpu = 92
ram = 71
disk = 53
severity = "critical"

[snapshot_2.decision]
action = "emergency_shutdown"
confidence = 0.88
justification = "CPU > 90 threshold + ReflexIA validation"
question_to_self = "Was emergency shutdown the only valid reaction? Should I try cooldown before restart?"

[snapshot_2.reflexia_feedback]
score = 0.92
conflict = false
alignment = "high"

[snapshot_2.alternatives]
actions = ["cooldown_mode", "reallocate_cores", "log_and_wait"]
last_decision = "cooldown_mode"
repetition_count = 0

[snapshot_2.memory_link]
global_context_path = "state/global_context.toml"
previous_snapshot = "zeroia_snapshot_20250625T14:45:02.toml"
