global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'arkalia-alerts@localhost'

route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      repeat_interval: 5m

receivers:
  - name: 'default'
    webhook_configs:
      - url: 'http://localhost:8000/alerts/webhook'
        send_resolved: true

  - name: 'critical-alerts'
    webhook_configs:
      - url: 'http://localhost:8000/alerts/critical'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'arkalia'
            password: 'secure-token'
