# 🚀 Arkalia-LUNA Pro - Docker Compose Simplifié et Optimisé
# Configuration garantie fonctionnelle

version: '3.8'

services:
  arkalia-master-enhanced:
    build:
      context: .
      dockerfile: Dockerfile.master
    container_name: arkalia-master-enhanced
    restart: unless-stopped
    ports:
      - "8000:8000" # Port principal
      - "9091:9091" # Port métriques Master
    volumes:
      - ./logs:/app/logs
      - ./state:/app/state
      - ./cache:/app/cache
      - ./config:/app/config
    environment:
      - PYTHONPATH=/app/modules:/app
      - PYTHONUNBUFFERED=1
      - ARKALIA_MODE=daemon
    healthcheck:
      test: [ "CMD", "python", "scripts/ark-master-orchestrator.py", "--mode", "status" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - arkalia-network

networks:
  arkalia-network:
    driver: bridge
