
[[decisions]]
output = "monitor"
[[decisions]]
output = "monitor"
[[decisions]]
output = "monitor"
[[decisions]]
output = "monitor"
[[decisions]]
output = "monitor"
[[decisions]]
output = "monitor"
[[decisions]]
output = "monitor"
[[decisions]]
output = "monitor"
[[decisions]]
output = "monitor"
[[decisions]]
output = "normal"
